# Build a docker image executing:
#   $ docker build -t tx-bot -f Dockerfile-tx-bot .
# docker run -it -e GITHUB_USER= -e GITHUB_TOKEN=### -e ORGANIZATION= -e TRANSIFEX_TEAM= -e TRANSIFEX_USER= -e TRANSIFEX_PASSWORD= tx-bot
#    /bin/sh -c "PYTHONPATH=/root/mt python -m tools.tx_pull -o ${ORGANIZATION}"
#
#FROM ubuntu:14.04
FROM tx-bot
#MAINTAINER Moises Lopez <moylop260@vauxoo.com>

#ENV MT_DIR /root/mt
ADD ./tools ${MT_DIR}/tools 
ADD ./requirements.txt ${MT_DIR}/mt_requirements.txt
#ENV PYTHONPATH ${PYTHONPATH}:${MT_DIR}

#RUN apt-get update
#RUN apt-get install -y build-essential python-dev python-pip \
#    && pip install --upgrade pip
#RUN pip install -r ${MT_DIR}/mt_requirements.txt

# ENTRYPOINT ["python -m tools.tx_pull -o ${ORGANIZATION}"]
RUN touch ${MT_DIR}/tx_pull && chmod +x ${MT_DIR}/tx_pull \ 
  && echo "#!/bin/sh\n" \
"if [ -z "\$ORGANIZATION" ]; then python -m tools.tx_pull; else python -m tools.tx_pull -o \${ORGANIZATION}; fi" \ 
> ${MT_DIR}/tx_pull

CMD ${MT_DIR}/tx_pull

# todo: Add aa cron
